<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Module;

class ModuleSeeder extends Seeder
{
    use WithoutModelEvents;
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      $modules = [
        [
          'name' => 'Dashboard',
          'slug' => 'dashboard',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 1,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'name' => 'Management',
          'icon' => 'ki-duotone ki-setting-4',
          'slug' => 'management',
          'display_order' => 2,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'name' => 'Configuration',
          'slug' => 'configuration',
          'icon' => 'ki-duotone ki-setting-4',
          'display_order' => 3,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'name' => 'Event Management',
          'slug' => 'event-management',
          'icon' => 'ki-duotone ki-setting-4',
          'display_order' => 4,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'name' => 'Procurement',
          'slug' => 'procurement',
          'icon' => 'ki-duotone ki-setting-4',
          'display_order' => 5,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'name' => 'Stock Control',
          'slug' => 'stock-control',
          'icon' => 'ki-duotone ki-setting-4',
          'display_order' => 6,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'name' => 'Reports',
          'slug' => 'reports',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 7,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 2,
          'name' => 'Modules',
          'icon' => 'fa-brands fa-superpowers',
          'slug' => 'modules',
          'display_order' => 1,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 2,
          'name' => 'Permissions',
          'icon' => 'fa-brands fa-superpowers',
          'slug' => 'permissions',
          'display_order' => 2,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 2,
          'name' => 'Roles',
          'icon' => 'fa-brands fa-superpowers',
          'slug' => 'roles',
          'display_order' => 3,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 2,
          'name' => 'Users',
          'icon' => 'fa-brands fa-superpowers',
          'slug' => 'users',
          'display_order' => 4,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Cuisines',
          'slug' => 'cuisines',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 1,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Dishes',
          'slug' => 'dishes',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 2,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Unit of Measures',
          'slug' => 'unit-of-measures',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 3,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Item Categories',
          'slug' => 'item-categories',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 4,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Items',
          'slug' => 'items',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 5,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Locations',
          'slug' => 'locations',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 6,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Places',
          'slug' => 'places',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 7,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Stores',
          'slug' => 'stores',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 8,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Kitchens',
          'slug' => 'kitchens',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 9,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Countries',
          'slug' => 'countries',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 10,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Cities',
          'slug' => 'cities',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 11,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Tiffin Sizes',
          'slug' => 'tiffin-sizes',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 12,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Designations',
          'slug' => 'designations',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 13,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Educations',
          'slug' => 'educations',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 14,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Currencies',
          'slug' => 'currencies',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 15,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Item UOMs',
          'slug' => 'item-base-uoms',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 16,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'UOMs Conversion',
          'slug' => 'uom-conversions',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 17,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 3,
          'name' => 'Serving Quantities',
          'slug' => 'serving-quantities',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 19,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 4,
          'name' => 'Recipes',
          'slug' => 'recipes',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 1,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 4,
          'name' => 'Events',
          'slug' => 'events',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 2,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 4,
          'name' => 'Menus',
          'slug' => 'menus',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 3,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 4,
          'name' => 'Menu Items',
          'slug' => 'menu-items',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 4,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 5,
          'name' => 'Vendors',
          'slug' => 'vendors',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 1,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 5,
          'name' => 'Vendor Contact Persons',
          'slug' => 'vendor-contact-persons',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 2,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 5,
          'name' => 'Vendor Banks',
          'slug' => 'vendor-banks',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 3,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 5,
          'name' => 'Open Purchase Orders',
          'slug' => 'open-purchase-orders',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 4,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 5,
          'name' => 'Event Purchase Orders',
          'slug' => 'purchase-orders',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 5,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],

        [
          'parent_id' => 6,
          'name' => 'Goods Received Notes',
          'slug' => 'goods-received-notes',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 1,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 6,
          'name' => 'Inventory',
          'slug' => 'inventories',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 2,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 6,
          'name' => 'Issued to Kitchens',
          'slug' => 'issued-to-kitchens',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 3,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 6,
          'name' => 'Goods Returned',
          'slug' => 'goods-returned',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 4,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
        [
          'parent_id' => 7,
          'name' => 'Inventory Report',
          'slug' => 'reports/inventory',
          'icon' => 'fa-brands fa-superpowers',
          'display_order' => 1,
          'is_active' => 1,
          'created_by' => 1,
          'updated_at' => null,
        ],
      ];
      foreach($modules as $key => $module){
          Module::firstOrCreate($module);
      }
    }
}
