<!DOCTYPE html>
<html>

<head>
  <title> Purchase Order</title>
  <style>
    body {
      font-family: DejaVu Sans, sans-serif;
    }

    h1 {
      color: red;
    }
  </style>
</head>

<body style="font-family: Arial, sans-serif;">

  <!-- Header Section -->
  <div style="width: 100%; border-bottom: 2px solid #d5d5d5; padding-bottom: 10px; margin-bottom: 10px;">
    <div style="float: left; width: 60%;">
      <h2 style="margin: 0 0 10px; color: #b98027;">{{$data['place']['name']}}</h2>
      <p style="margin: 0 0 10px; color: #000;">{{isset($data['place']['location']['area']) ? $data['place']['location']['area'] : ""}}, {{isset($data['place']['location']['country']['name']) ? $data['place']['location']['country']['name'] : ""}}, {{isset($data['place']['location']['country']['city']['name']) ? $data['place']['location']['country']['city']['name'] : ""}}</p>

    </div>
    <div style="float: right; width: 40%; text-align: right;">
      <h3 style="margin: 0; color: #b98027;">PURCHASE ORDER</h3>
    </div>
    <div style="clear: both;"></div>
    <table
      style="width: 100%;">
      <tr>
        <td style="">
          <b style=""> Phone:</b> {{isset($data['place']['contact_no']) ? $data['place']['contact_no'] : ""}}
        </td>
      </tr>
    </table>
    <div style="clear: both;"></div>
  </div>

  <!-- Purchase Order Information -->
  <table style="width: 100%; margin-bottom: 10px; background-color: #b98027; padding: 10px; border-radius: 5px;">
    <tr>
      <td style="width: 50%;">
        <p style="margin: 0; font-size: 16px; color: #fff;"><strong>PO No: </strong>{{$data['purchaseDetail']['id']}}</p>
      </td>
      <td style="width: 50%; text-align: right;">
        <p style="margin: 0; font-size: 16px; color: #fff;"><strong>Date: </strong>{{ \Carbon\Carbon::parse($data['purchaseDetail']['created_at'])->isoFormat('Do MMM YYYY') }}</p>
      </td>
    </tr>
  </table>

  <!-- Purchase From and Ship To -->
  <table style="width: 100%; margin-bottom: 10px; border-collapse: collapse;">
    <tr>
      <td style="width: 50%; padding: 10px 0; vertical-align: baseline;">
        <b style="color: #b98027;margin-bottom: 5px;display: inline-block; font-size: 16px;text-transform:uppercase">Purchase From</b><br>
        <b style="margin: 5px 0;display: inline-block;"> {{$data['vendorDetail']['contact_person']['name']}}</b><br>
        <span style="margin-top: 7px;display: inline-block;">{{$data['vendorDetail']['address']}}</span><br>
        <span style="margin-top: 7px;display: inline-block;">Phone: {{$data['vendorDetail']['contact_person']['contact_number']}}</span><br>
        <span style="margin-top: 7px;display: inline-block;">Office: {{$data['vendorDetail']['contact_person']['office_number']}}</span><br>
        @if(!empty($data['vendorDetail']['bank']['ntn']))
          <span style="margin-top: 7px; display: inline-block;">NTN: {{$data['vendorDetail']['bank']['ntn']}}</span><br>
        @endif

      </td>
      <td style="width: 50%; padding: 10px; vertical-align: baseline;">
        <b style="color: #b98027;margin-bottom: 5px;display: inline-block;font-size: 16px;text-transform:uppercase">Ship To</b><br>
        <b style="margin: 5px 0;display: inline-block;"> {{$data['place']['name']}}</b><br>
        <span style="margin-top: 7px;display: inline-block;">{{isset($data['place']['location']['area']) ? $data['place']['location']['area'] : ""}}, {{isset($data['place']['location']['country']['name']) ? $data['place']['location']['country']['name'] : ""}}, {{isset($data['place']['location']['country']['city']['name']) ? $data['place']['location']['country']['city']['name'] : ""}}</span><br>
        <!-- <span style="margin-top: 7px;display: inline-block;">Generated By: {{$data['userName']}}</span><br> -->
      </td>
    </tr>
  </table>

  <!-- Items Table -->
  <table style="width: 100%; border-collapse: collapse; margin-bottom: 10px;">
    <thead>
      <tr style="background-color: #b98027; color: #fff;">
        <th style="border: 1px solid #d5d5d5; padding: 10px; text-align: left;">Items</th>
        <th style="border: 1px solid #d5d5d5; padding: 10px; text-align: center;">Qty</th>
        <th style="border: 1px solid #d5d5d5; padding: 10px; text-align: center;">Unit</th>
        <th style="border: 1px solid #d5d5d5; padding: 10px; text-align: center;">Price per Unit</th>
        <th style="border: 1px solid #d5d5d5; padding: 10px; text-align: right;">Amount</th>
      </tr>
    </thead>
    <tbody>
      @foreach($data['itemInfos'] as $itemInfo)
      <tr>
        <td style="border: 1px solid #b98027; padding: 10px;">{{ $itemInfo['item'] }}</td>
        <td style="border: 1px solid #b98027; padding: 10px; text-align: center;">{{ $itemInfo['quantity'] }}</td>
        <td style="border: 1px solid #b98027; padding: 10px; text-align: center;">{{ $itemInfo['unit_measure'] }}</td>
        <td style="border: 1px solid #b98027; padding: 10px; text-align: center;">{{ $itemInfo['unit_price'] }}</td>
        <td style="border: 1px solid #b98027; padding: 10px; text-align: right;"> {{number_format( $itemInfo['total'], 2) }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <div>
    <div style="float: left; width: 60%;">
      @if(isset($data['vendorDetail']['bank']))
        <!-- Bank Details -->
        <div style="margin-bottom: 10px;">
          <b style="margin: 5px 0;display: inline-block;"> Bank Details</b><br>
          <span style="margin-top: 5px;display: inline-block;">Account Title: {{$data['vendorDetail']['bank']['bank_title']}}</span><br>
          <span style="margin-top: 5px;display: inline-block;">Account Number: {{$data['vendorDetail']['bank']['account_no']}}</span><br>
          <span style="margin-top: 5px;display: inline-block;">Bank: {{$data['vendorDetail']['bank']['bank']}}</span><br>
          <span style="margin-top: 5px;display: inline-block;">Branch: {{$data['vendorDetail']['bank']['bank_branch']}} </span><br>
          <span style="margin-top: 5px;display: inline-block;">Bank Address: {{$data['vendorDetail']['bank']['bank_address']}}</span><br>
        </div>
      @endif
      <!-- Terms & Conditions -->
      <div>
        <b style="margin: 5px 0;display: inline-block;"> Terms & Conditions</b><br>
        <ol style="margin: 0; padding-left: 20px;">
          <li style="margin-top: 5px;">Customer will pay the GST</li>
          <li style="margin-top: 5px;">Customer will pay the Delivery charges</li>
          <li style="margin-top: 5px;">Pay due amount within 15 days</li>
        </ol>
      </div>

    </div>
    <div style="float: right; width: 40%; text-align: right;">
      <table width="100%">
        <tr>
          <td style="padding:3px 0">Sub Total</td>
          <td style="text-align: right;">{{ number_format($data['totalAmount'] + $data['purchaseDetail']['discount'], 2) }}</td>
        </tr>
        <tr>
          <td style="padding:3px 0">Discount</td>
          <td style="text-align: right;">- {{number_format( $data['purchaseDetail']['discount'], 2)}}</td>
        </tr>
        <tr>
          <td style="font-weight: bold;border-top:1px solid #b98027;border-bottom:1px solid #b98027;padding:10px 0">Total Amount </td>
          <td style="text-align: right;font-weight: bold;border-top:1px solid #b98027;border-bottom:1px solid #b98027;padding:10px 0">{{isset($data['currency']['short_form']) ? $data['currency']['short_form'] : ""}} {{ number_format($data['totalAmount'], 2) }}</td>
        </tr>
      </table>
    </div>
  </div>


</body>

</html>